export class PieceRepo {
  static readonly repo: any = {
    a1 : 'rook-l',
    b1 : 'knight-l',
    c1 : 'bishop-l',
    d1 : 'queen-l',
    e1 : 'king-l',
    f1 : 'bishop-l',
    g1 : 'knight-l',
    h1 : 'rook-l',
    a8 : 'rook-d',
    b8 : 'knight-d',
    c8 : 'bishop-d',
    d8 : 'queen-d',
    e8 : 'king-d',
    f8 : 'bishop-d',
    g8 : 'knight-d',
    h8 : 'rook-d',
    a2 : 'pawn-l',
    b2 : 'pawn-l',
    c2 : 'pawn-l',
    d2 : 'pawn-l',
    e2 : 'pawn-l',
    f2 : 'pawn-l',
    g2 : 'pawn-l',
    h2 : 'pawn-l',
    a7: 'pawn-d',
    b7: 'pawn-d',
    c7: 'pawn-d',
    d7: 'pawn-d',
    e7: 'pawn-d',
    f7: 'pawn-d',
    g7: 'pawn-d',
    h7: 'pawn-d',
  };
}
